/// Flutter icons Gym
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family: Gym
///      fonts:
///       - asset: fonts/Gym.ttf
///
import 'package:flutter/widgets.dart';

class GymIcons {
  GymIcons._();

  static const _kFontFam = 'Gym';

  static const IconData dumbbell =
      const IconData(0xe800, fontFamily: _kFontFam);
}
