/// Flutter icons Gym
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family: Gym
///      fonts:
///       - asset: fonts/Gym.ttf
///
import 'package:flutter/widgets.dart';

class GymIcons {
  GymIcons._();

  static const _kFontFam = 'Gym';

  static const IconData meal = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData equipment = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData machine = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bar = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cable = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData kettlebell = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData weightplate = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData ezbar = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData barbell = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData exerciseball = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData dumbbell = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData bodyonly = const IconData(0xe813, fontFamily: _kFontFam);
}
